### ISSUE TITLE
Exception on Ubuntu 22.04

### ISSUE THREAD

**Issue by kitzberger** [k-kirill/anki-libunity#7]
Just installed in on Ubuntu 22.04 and had this exception:

```
Traceback (most recent call last):
  File "/usr/share/anki/aqt/addons.py", line 80, in loadAddons
    __import__(dir)
  File "/home/philipp/.local/share/Anki2/addons21/901237400/__init__.py", line 2, in <module>
    from aqt import gui_hooks
ImportError: cannot import name 'gui_hooks' from 'aqt' (/usr/share/anki/aqt/__init__.py)
```

Anki version: 2.1.5

**Comment by kitzberger** [comment]
Upgrading anki to 2.1.54 solved the issue.
